server:
  port: 9001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

  

  
spring:
  cloud:
    gateway:
      routes:
      - id: AdminContact-Service
        uri:
          http://localhost:8080/
        predicates:
        - Path=/contacts/**
        
        
        
       
      - id: TrainDetails
        uri:
          http://localhost:8888/
        predicates:
        - Path=/trains/**
        
         
        