server:
  port: 9069
spring:
  application:
    name: PAYTM-PAYMENT
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost